name = "lively-mouse-0c7c"
main = "worker.js"
compatibility_date = "2024-09-23"

[[d1_databases]]
binding = "DB"
database_name = "aykan-db"
database_id = "058e06bb-6148-4c5b-ba34-e1321bb9ac7c"

[assets]
directory = "./public"
